<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../build/TestProject.props" />

  <PropertyGroup>
    <RootNamespace>Enver.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Enver.Extensions.Configuration/Enver.Extensions.Configuration.csproj" />
  </ItemGroup>
</Project>
