using System.CodeDom.Compiler;
using Enver.Binding.Generator.Model;

namespace Enver.Binding.Generator;

internal static class Emitter
{
    public static string Emit(BindingHost host)
    {
        using var sw = new StringWriter();
        using var w = new IndentedTextWriter(sw);

        w.WriteLine("// <auto-generated/>");
        w.WriteLine("#nullable enable");
        w.WriteLine("#pragma warning disable CS8601 // Possible null reference assignment");
        w.WriteLine(
            "#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor"
        );
        w.WriteLine(
            "#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member"
        );
        w.WriteLine();

        if (host.HostNamespace.Length > 0)
        {
            w.WriteLine($"namespace {host.HostNamespace};");
            w.WriteLine();
        }

        // Open the enclosing type chain.
        int enclosingDepth = 0;
        foreach (var enc in host.EnclosingTypes.AsImmutableArray())
        {
            w.WriteLine($"partial {enc.Keyword} {enc.Name}");
            w.WriteLine("{");
            w.Indent++;
            enclosingDepth++;
        }

        // Open the host partial.
        w.WriteLine($"partial {host.HostKeyword} {host.HostName}");
        w.WriteLine("{");
        w.Indent++;

        // Self-bind hosts get the plain Bind/Binder names; external hosts
        // ([EnvBindable<T>]) suffix them with the target's simple name.
        var target = host.Target;
        var methodInfix = host.HostIsSelfBindable ? "" : target.SimpleTypeName;
        var binderName = host.HostIsSelfBindable ? "Binder" : $"{target.SimpleTypeName}Binder";
        EmitStaticMethods(w, target, methodInfix, binderName);
        w.WriteLine();
        EmitBinderClass(w, target, binderName);
        EmitValidateHelpers(w, target);

        // Close host partial + enclosing types.
        w.Indent--;
        w.WriteLine("}");
        for (int i = 0; i < enclosingDepth; i++)
        {
            w.Indent--;
            w.WriteLine("}");
        }

        return sw.ToString();
    }

    #region Static helper methods

    private static void EmitStaticMethods(
        IndentedTextWriter w,
        BindingTarget target,
        string methodInfix,
        string binderName
    )
    {
        var t = target.FullyQualifiedTypeName;

        // Bind(IEnvReader)
        w.WriteLine("/// <summary>Bind a fresh instance from an existing reader.</summary>");
        w.WriteLine($"public static {t} Bind{methodInfix}(global::Enver.IEnvReader reader)");
        w.WriteLine("{");
        w.Indent++;
        w.Write("return ");
        EmitInlineObjectConstructionForReader(w, target);
        w.WriteLine(";");
        w.Indent--;
        w.WriteLine("}");
        w.WriteLine();

        // Bind(string path)
        w.WriteLine(
            "/// <summary>Bind a fresh instance by loading the given .env file. "
                + "Missing files are silently skipped.</summary>"
        );
        w.WriteLine(
            $"public static {t} Bind{methodInfix}("
                + "string path, "
                + "global::Enver.Parsing.EnvParseOptions parseOptions = default)"
        );
        w.WriteLine("{");
        w.Indent++;
        w.WriteLine($"var binder = new {binderName}();");
        w.WriteLine("global::Enver.Loading.EnvFileLoader.Load(binder, path, parseOptions);");
        w.WriteLine("return binder.Build();");
        w.Indent--;
        w.WriteLine("}");
        w.WriteLine();

        // Bind(IEnumerable<string> paths)
        w.WriteLine(
            "/// <summary>Bind a fresh instance by loading each .env file in order; "
                + "later files override values defined in earlier ones, with shared "
                + "<c>${VAR}</c> interpolation across the whole sequence. Missing files are "
                + "silently skipped. Pair with <see cref=\"global::Enver.DotEnvPaths\"/> "
                + "to compose the canonical ladder.</summary>"
        );
        w.WriteLine(
            $"public static {t} Bind{methodInfix}("
                + "global::System.Collections.Generic.IEnumerable<string> paths, "
                + "global::Enver.Parsing.EnvParseOptions parseOptions = default)"
        );
        w.WriteLine("{");
        w.Indent++;
        w.WriteLine($"var binder = new {binderName}();");
        w.WriteLine("global::Enver.Loading.EnvFileLoader.Load(binder, paths, parseOptions);");
        w.WriteLine("return binder.Build();");
        w.Indent--;
        w.WriteLine("}");

        if (target.GeneratePopulate)
        {
            w.WriteLine();
            EmitPopulateStaticMethod(w, target, methodInfix);
        }
    }

    private static void EmitInlineObjectConstructionForReader(
        IndentedTextWriter w,
        BindingTarget target
    )
    {
        var validate = RequiresValidation(target);
        if (validate)
        {
            w.Write("__Validate(");
        }
        w.Write($"new {target.FullyQualifiedTypeName}(");
        var ctorNames = target.Construction.CtorParameterMemberNames.AsImmutableArray();
        for (int i = 0; i < ctorNames.Length; i++)
        {
            if (i > 0)
            {
                w.Write(", ");
            }

            var memberName = ctorNames[i];
            w.Write($"{memberName}: ");
            EmitInlineMemberInitializationForReader(w, target, memberName);
        }
        w.Write(")");

        var initNames = target.Construction.ObjectInitializerMemberNames.AsImmutableArray();
        if (initNames.Length != 0)
        {
            w.WriteLine();
            w.WriteLine("{");
            w.Indent++;
            foreach (var memberName in initNames)
            {
                w.Write($"{memberName} = ");
                EmitInlineMemberInitializationForReader(w, target, memberName);
                w.WriteLine(",");
            }
            w.Indent--;
            w.Write("}");
        }
        if (validate)
        {
            w.Write(")");
        }
    }

    private static void EmitInlineMemberInitializationForReader(
        IndentedTextWriter w,
        BindingTarget target,
        string memberName
    )
    {
        var member = TryFindMember(target, memberName);
        if (member is not null)
        {
            EmitInlineCallExpressionForReader(w, member, target);
        }
        else
        {
            foreach (var sub in target.SubSections.AsImmutableArray())
            {
                if (sub.MemberName == memberName)
                {
                    EmitInlineObjectConstructionForReader(w, sub.Target);
                    return;
                }
            }
            throw new InvalidOperationException(
                $"SubSection '{memberName}' not found in target '{target.SimpleTypeName}'."
            );
        }
    }

    private static void EmitInlineCallExpressionForReader(
        IndentedTextWriter w,
        BindingMember m,
        BindingTarget target
    )
    {
        var isOptional = ResolveRequirement(m) is EffectiveRequirement.Optional;

        w.Write("global::Enver.EnvReaderExtensions.Get");
        if (isOptional)
        {
            w.Write("Optional");
        }

        w.Write(ReaderMethod(m, isOptional));
        w.Write($"(reader, \"{m.ResolvedKey}\"");
        if (m.Dispatch == TypeDispatchKind.Uri)
        {
            w.Write(", ");
            w.Write(UriKindExpression(m));
        }
        if (TypeDispatch.UsesFormatProvider(m.Dispatch))
        {
            w.Write(", ");
            var fp = m.FormatProvider ?? target.DefaultFormatProvider;
            w.Write(
                fp is null
                    ? "default(global::System.IFormatProvider)"
                    : $"{fp.TypeFullyQualifiedName}.{fp.MemberName}"
            );
        }
        w.Write(")");

        // GetOptional* returns T?. When the target member is non-nullable (an
        // optional value type) or declares a C# initializer, fall back to the
        // declared default so the result is the member's type and the default
        // is honored.
        if (isOptional && (m.CSharpInitializerExpression is not null || !m.TypeIsNullable))
        {
            w.Write($" ?? {m.CSharpInitializerExpression ?? "default"}");
        }
    }

    private static string ReaderMethod(BindingMember m, bool isOptional)
    {
        return m.Dispatch switch
        {
            TypeDispatchKind.String => "String",
            TypeDispatchKind.Boolean => "Boolean",
            TypeDispatchKind.Guid => "Guid",
            TypeDispatchKind.Uri => "Uri",
            TypeDispatchKind.Version => "Version",
            TypeDispatchKind.Enum => $"Enum<{m.UnderlyingTypeFullyQualifiedName}>",
            TypeDispatchKind.Number => $"Number<{m.UnderlyingTypeFullyQualifiedName}>",
            // char and any IUtf8SpanParsable / ISpanParsable / IParsable type
            // bind through the generic Get<T> entry point.
            TypeDispatchKind.Utf8SpanParsable
            or TypeDispatchKind.SpanParsable
            or TypeDispatchKind.Parsable =>
                $"{(isOptional && !m.UnderlyingIsValueType ? "Ref" : "")}<{m.UnderlyingTypeFullyQualifiedName}>",
            _ => throw new InvalidOperationException(), // Unsupported is filtered before emit
        };
    }

    private static string UriKindExpression(BindingMember m) =>
        $"global::System.UriKind.{m.UriKind ?? UriKind.Absolute}";

    private static string? FormatProviderExpression(BindingMember m, BindingTarget target)
    {
        if (!TypeDispatch.UsesFormatProvider(m.Dispatch))
        {
            return null;
        }
        var fp = m.FormatProvider ?? target.DefaultFormatProvider;
        return fp is null ? null : $"{fp.TypeFullyQualifiedName}.{fp.MemberName}";
    }

    #endregion

    #region Binder

    private static void EmitBinderClass(
        IndentedTextWriter w,
        BindingTarget target,
        string binderName
    )
    {
        w.WriteLine(
            "/// <summary>Generated EnvParser that accumulates values and builds the target.</summary>"
        );
        w.WriteLine($"public sealed partial class {binderName} : global::Enver.Parsing.EnvParser");
        w.WriteLine("{");
        w.Indent++;

        EmitBinderMemberFields(w, target);

        EmitOnNext(w, target);
        w.WriteLine();
        EmitBuildMethod(w, target);

        if (target.GeneratePopulate)
        {
            w.WriteLine();
            EmitPopulateOnBinder(w, target);
        }

        w.Indent--;
        w.WriteLine("}");
    }

    // -- Populate (static, IEnvReader path) --

    private static void EmitPopulateStaticMethod(
        IndentedTextWriter w,
        BindingTarget target,
        string methodInfix
    )
    {
        var t = target.FullyQualifiedTypeName;
        w.WriteLine(
            "/// <summary>Populate the mutable members of an existing instance from a reader.</summary>"
        );
        w.WriteLine(
            $"public static void Populate{methodInfix}({t} instance, global::Enver.IEnvReader reader)"
        );
        w.WriteLine("{");
        w.Indent++;

        foreach (var m in target.Members.AsImmutableArray())
        {
            if (!m.IsInitOnly)
            {
                w.Write($"instance.{m.MemberName} = ");
                EmitInlineCallExpressionForReader(w, m, target);
                w.WriteLine(";");
            }
        }

        foreach (var sub in target.SubSections.AsImmutableArray())
        {
            if (!sub.IsInitOnly)
            {
                w.Write($"instance.{sub.MemberName} = ");
                EmitInlineObjectConstructionForReader(w, sub.Target);
                w.WriteLine(";");
            }
        }

        w.Indent--;
        w.WriteLine("}");
    }

    // -- Populate (Binder instance method) --

    private static void EmitPopulateOnBinder(IndentedTextWriter w, BindingTarget target)
    {
        var t = target.FullyQualifiedTypeName;
        w.WriteLine(
            "/// <summary>Populate the mutable members of an existing instance from accumulated values.</summary>"
        );
        w.WriteLine($"public void Populate({t} instance)");
        w.WriteLine("{");
        w.Indent++;

        // Flat mutable members: assign only if the value was parsed.
        foreach (var m in target.Members.AsImmutableArray())
        {
            if (!m.IsInitOnly)
            {
                w.WriteLine(
                    $"if (_set_{m.MemberName}) instance.{m.MemberName} = _val_{m.MemberName}!;"
                );
            }
        }

        // Mutable subsection properties: construct and assign if any leaf value was parsed.
        foreach (var sub in target.SubSections.AsImmutableArray())
        {
            if (!sub.IsInitOnly)
            {
                EmitPopulateSubSectionOnBinder(w, sub);
            }
        }

        w.Indent--;
        w.WriteLine("}");
    }

    private static void EmitPopulateSubSectionOnBinder(IndentedTextWriter w, SubSection sub)
    {
        // Condition: at least one leaf field in the subsection tree was parsed.
        var conditions = new List<string>();
        CollectSetConditions(sub.Target, sub.MemberName + "_", conditions);

        if (conditions.Count > 0)
        {
            w.WriteLine($"if ({string.Join(" || ", conditions)})");
            w.WriteLine("{");
            w.Indent++;
        }

        EmitPopulateSubSectionLocals(w, sub, null);
        w.WriteLine($"instance.{sub.MemberName} = _built_{sub.MemberName};");

        if (conditions.Count > 0)
        {
            w.Indent--;
            w.WriteLine("}");
        }
    }

    private static void EmitPopulateSubSectionLocals(
        IndentedTextWriter w,
        SubSection sub,
        string? fieldPrefix
    )
    {
        var localFieldPrefix = fieldPrefix + sub.MemberName + "_";

        // Recurse: build deeper subsection locals first.
        foreach (var nested in sub.Target.SubSections.AsImmutableArray())
        {
            EmitPopulateSubSectionLocals(w, nested, localFieldPrefix);
        }

        var localVarName = $"_built_{fieldPrefix}{sub.MemberName}";
        w.Write($"var {localVarName} = ");
        EmitBuildConstruction(w, sub.Target, localFieldPrefix);
        w.WriteLine(";");
    }

    private static void CollectSetConditions(
        BindingTarget target,
        string fieldPrefix,
        List<string> conditions
    )
    {
        foreach (var m in target.Members.AsImmutableArray())
        {
            conditions.Add($"_set_{fieldPrefix}{m.MemberName}");
        }
        foreach (var sub in target.SubSections.AsImmutableArray())
        {
            CollectSetConditions(sub.Target, fieldPrefix + sub.MemberName + "_", conditions);
        }
    }

    // -- Subsection field emission --

    private static void EmitBinderMemberFields(
        IndentedTextWriter w,
        BindingTarget target,
        string? fieldPrefix = null
    )
    {
        foreach (var m in target.Members.AsImmutableArray())
        {
            var fieldType = StorageTypeOf(m);
            w.WriteLine($"// {m.ResolvedKey} -> {fieldPrefix}{m.MemberName}");
            w.WriteLine($"private {fieldType} _val_{fieldPrefix}{m.MemberName};");
            w.WriteLine($"private bool _set_{fieldPrefix}{m.MemberName};");
            w.WriteLine();
        }
        foreach (var nested in target.SubSections.AsImmutableArray())
        {
            EmitBinderMemberFields(w, nested.Target, fieldPrefix + nested.MemberName + "_");
        }
    }

    // -- OnNext --

    private static void EmitOnNext(IndentedTextWriter w, BindingTarget target)
    {
        w.WriteLine(
            "protected override bool OnNext(global::System.ReadOnlySpan<byte> key, ref global::Enver.Parsing.EnvValueReader value)"
        );
        w.WriteLine("{");
        w.Indent++;
        EmitOnNextCases(w, target);
        w.WriteLine("return true;");
        w.Indent--;
        w.WriteLine("}");
    }

    private static void EmitOnNextCases(
        IndentedTextWriter w,
        BindingTarget target,
        string? fieldPrefix = null
    )
    {
        foreach (var m in target.Members.AsImmutableArray())
        {
            w.WriteLine(
                $"if (global::System.MemoryExtensions.SequenceEqual(key, \"{m.ResolvedKey}\"u8))"
            );
            w.WriteLine("{");
            w.Indent++;
            EmitParseAndAssign(w, m, target, fieldPrefix);
            w.WriteLine($"_set_{fieldPrefix}{m.MemberName} = true;");
            w.WriteLine("return true;");
            w.Indent--;
            w.WriteLine("}");
        }
        foreach (var nested in target.SubSections.AsImmutableArray())
        {
            EmitOnNextCases(w, nested.Target, fieldPrefix + nested.MemberName + "_");
        }
    }

    private static void EmitParseAndAssign(
        IndentedTextWriter w,
        BindingMember m,
        BindingTarget target,
        string? fieldPrefix = null
    )
    {
        var assign = $"_val_{fieldPrefix}{m.MemberName}";
        w.WriteLine("try");
        w.WriteLine("{");
        w.Indent++;
        w.WriteLine($"{assign} = {ParseSpanExpression(m, target)};");
        w.Indent--;
        w.WriteLine("}");
        w.WriteLine(
            "catch (global::System.Exception __ex) when (__ex is not global::Enver.EnvException)"
        );
        w.WriteLine("{");
        w.Indent++;
        w.WriteLine(
            $"throw new global::Enver.EnvInvalidValueException(\"{m.ResolvedKey}\", \"invalid {m.UnderlyingTypeDisplayName} value\", __ex);"
        );
        w.Indent--;
        w.WriteLine("}");
    }

    /// <summary>
    /// Right-hand side of <c>_val_X = ...;</c>
    /// </summary>
    private static string ParseSpanExpression(BindingMember m, BindingTarget target)
    {
        var fp = FormatProviderExpression(m, target);
        var providerArg = fp is null ? "" : $", {fp}";
        return m.Dispatch switch
        {
            TypeDispatchKind.String => "value.AsString()",
            // bool implements ISpanParsable<bool> but not IUtf8SpanParsable<bool>,
            // so it parses through the UTF-16 bridge rather than a UTF-8 overload.
            TypeDispatchKind.Boolean =>
                "global::Enver.Parsing.EnvValueParser.ParseISpanParsable<global::System.Boolean>(value.Span)",
            TypeDispatchKind.Number =>
                $"global::Enver.Parsing.EnvValueParser.ParseNumberWithPrefix<{m.UnderlyingTypeFullyQualifiedName}>(value.Span{providerArg})",
            TypeDispatchKind.Guid => "global::Enver.Parsing.EnvValueParser.ParseGuid(value.Span)",
            TypeDispatchKind.Uri =>
                $"new global::System.Uri(value.AsString(), {UriKindExpression(m)})",
            TypeDispatchKind.Version =>
                "global::Enver.Parsing.EnvValueParser.ParseVersion(value.Span)",
            TypeDispatchKind.Enum =>
                $"global::Enver.Parsing.EnvValueParser.ParseDefinedEnum<{m.UnderlyingTypeFullyQualifiedName}>(value.Span)",
            TypeDispatchKind.Utf8SpanParsable =>
                $"global::Enver.Parsing.EnvValueParser.ParseIUtf8SpanParsable<{m.UnderlyingTypeFullyQualifiedName}>(value.Span{providerArg})",
            TypeDispatchKind.SpanParsable =>
                $"global::Enver.Parsing.EnvValueParser.ParseISpanParsable<{m.UnderlyingTypeFullyQualifiedName}>(value.Span{providerArg})",
            TypeDispatchKind.Parsable =>
                $"{m.UnderlyingTypeFullyQualifiedName}.Parse(value.AsString(), {fp ?? "default(global::System.IFormatProvider?)"})",
            _ => "value.AsString()",
        };
    }

    // -- Build --

    private static void EmitBuildMethod(IndentedTextWriter w, BindingTarget target)
    {
        w.WriteLine($"public {target.FullyQualifiedTypeName} Build()");
        w.WriteLine("{");
        w.Indent++;

        // Check required flat members.
        foreach (var m in target.Members.AsImmutableArray())
        {
            if (ResolveRequirement(m) == EffectiveRequirement.Required)
            {
                w.WriteLine(
                    $"if (!_set_{m.MemberName}) throw new global::Enver.EnvMissingVariableException(\"{m.ResolvedKey}\", \"missing required env variable '{m.ResolvedKey}'\");"
                );
            }
        }

        // Build subsection locals (checks their required members, then constructs).
        foreach (var sub in target.SubSections.AsImmutableArray())
        {
            EmitSubSectionBuildLocal(w, sub);
        }

        // Construct the root target.
        w.Write("return ");
        EmitBuildConstruction(w, target);
        w.WriteLine(";");
        w.Indent--;
        w.WriteLine("}");
    }

    private static void EmitSubSectionBuildLocal(
        IndentedTextWriter w,
        SubSection sub,
        string? fieldPrefix = null
    )
    {
        var localFieldPrefix = fieldPrefix + sub.MemberName + "_";

        // Check required leaf members of this subsection.
        foreach (var m in sub.Target.Members.AsImmutableArray())
        {
            if (ResolveRequirement(m) == EffectiveRequirement.Required)
            {
                w.WriteLine(
                    $"if (!_set_{localFieldPrefix}{m.MemberName}) throw new global::Enver.EnvMissingVariableException(\"{m.ResolvedKey}\", \"missing required env variable '{m.ResolvedKey}'\");"
                );
            }
        }

        // Recurse: build deeper subsection locals first.
        foreach (var nested in sub.Target.SubSections.AsImmutableArray())
        {
            EmitSubSectionBuildLocal(w, nested, localFieldPrefix);
        }

        // Construct the subsection local.
        var localVarName = $"_built_{fieldPrefix}{sub.MemberName}";
        w.Write($"var {localVarName} = ");
        EmitBuildConstruction(w, sub.Target, localFieldPrefix);
        w.WriteLine(";");
    }

    private static void EmitBuildConstruction(
        IndentedTextWriter w,
        BindingTarget target,
        string? fieldPrefix = null
    )
    {
        var validate = RequiresValidation(target);
        if (validate)
        {
            w.Write("__Validate(");
        }
        w.Write($"new {target.FullyQualifiedTypeName}(");
        var ctorNames = target.Construction.CtorParameterMemberNames.AsImmutableArray();
        for (int i = 0; i < ctorNames.Length; i++)
        {
            if (i > 0)
            {
                w.Write(", ");
            }
            w.Write($"{ctorNames[i]}: {BuildBuildExpression(target, ctorNames[i], fieldPrefix)}");
        }
        w.Write(")");

        var initNames = target.Construction.ObjectInitializerMemberNames.AsImmutableArray();
        if (initNames.Length > 0)
        {
            w.WriteLine();
            w.WriteLine("{");
            w.Indent++;
            foreach (string memberName in initNames)
            {
                w.WriteLine(
                    $"{memberName} = {BuildBuildExpression(target, memberName, fieldPrefix)},"
                );
            }
            w.Indent--;
            w.Write("}");
        }
        if (validate)
        {
            w.Write(")");
        }
    }

    private static string BuildBuildExpression(
        BindingTarget target,
        string memberName,
        string? fieldPrefix = null
    )
    {
        var m = TryFindMember(target, memberName);
        if (m is not null)
        {
            var field = $"_val_{fieldPrefix}{memberName}";
            if (ResolveRequirement(m) is EffectiveRequirement.Required)
            {
                return field;
            }
            var defaultExpr = m.CSharpInitializerExpression ?? "default";
            if (!m.TypeIsNullable && m.UnderlyingIsValueType)
            {
                // Optional non-nullable value types are stored as Nullable<T> (see
                // StorageTypeOf), so the conditional would be T? against a T target.
                // Unwrap to T; the _set guard guarantees it is non-null on that
                // branch.
                return $"_set_{fieldPrefix}{memberName} ? {field}!.Value : {defaultExpr}";
            }
            return $"_set_{fieldPrefix}{memberName} ? {field} : {defaultExpr}";
        }
        else
        {
            // TODO: subsection optional + default expression support
            return $"_built_{fieldPrefix}{memberName}";
        }
    }

    #endregion

    #region Validation

    private static bool RequiresValidation(BindingTarget target)
    {
        if (target.ImplementsIValidatableObject)
        {
            return true;
        }
        foreach (var m in target.Members.AsImmutableArray())
        {
            if (m.Validators.Length > 0)
            {
                return true;
            }
        }
        return false;
    }

    private static void EmitValidateHelpers(IndentedTextWriter w, BindingTarget root)
    {
        // One __Validate(T) overload per distinct validating target (root +
        // subsections). Each target validates itself; nesting works because every
        // construction site wraps in __Validate when its target requires it.
        var emitted = new HashSet<string>(StringComparer.Ordinal);
        int validatorFieldCounter = 0;
        CollectAndEmit(w, root, emitted, ref validatorFieldCounter);
    }

    private static void CollectAndEmit(
        IndentedTextWriter w,
        BindingTarget target,
        HashSet<string> emitted,
        ref int fieldCounter
    )
    {
        if (RequiresValidation(target) && emitted.Add(target.FullyQualifiedTypeName))
        {
            w.WriteLine();
            EmitValidateMethod(w, target, ref fieldCounter);
        }
        foreach (var sub in target.SubSections.AsImmutableArray())
        {
            CollectAndEmit(w, sub.Target, emitted, ref fieldCounter);
        }
    }

    private static void EmitValidateMethod(
        IndentedTextWriter w,
        BindingTarget target,
        ref int fieldCounter
    )
    {
        const string ctxType = "global::System.ComponentModel.DataAnnotations.ValidationContext";
        var t = target.FullyQualifiedTypeName;

        var membersWithValidators = target
            .Members.AsImmutableArray()
            .Where(m => m.Validators.Length > 0)
            .ToArray();

        // Each validator attribute is constructed once into a static field and
        // reused across binds. fieldNames[memberIndex][validatorIndex] holds the
        // generated field name.
        var fieldNames = new string[membersWithValidators.Length][];
        for (int mi = 0; mi < membersWithValidators.Length; mi++)
        {
            var validators = membersWithValidators[mi].Validators.AsImmutableArray();
            fieldNames[mi] = new string[validators.Length];
            for (int vi = 0; vi < validators.Length; vi++)
            {
                var v = validators[vi];
                // CustomValidation calls a user method directly - no attribute is
                // constructed, so it gets no static field.
                if (v.Synthesis is CustomValidationCheck)
                {
                    continue;
                }
                var ctorArgs = string.Join(
                    ", ",
                    v.ConstructorArgumentExpressions.AsImmutableArray()
                );
                var named = v.NamedArgumentExpressions.AsImmutableArray();
                var initializer =
                    named.Length == 0
                        ? ""
                        : " { "
                            + string.Join(", ", named.Select(n => $"{n.Name} = {n.Expression}"))
                            + " }";
                var field = $"__validator{fieldCounter++}";
                fieldNames[mi][vi] = field;
                var decl =
                    $"private static readonly {v.AttributeTypeFullyQualifiedName} {field} = "
                    + $"new {v.AttributeTypeFullyQualifiedName}({ctorArgs}){initializer};";
                if (v.Synthesis is not null)
                {
                    // attributes are only used for FormatErrorMessage - safe to use
                    w.WriteLine("#pragma warning disable IL2026");
                    w.WriteLine(decl);
                    w.WriteLine("#pragma warning restore IL2026");
                }
                else
                {
                    w.WriteLine(decl);
                }
            }
        }

        // A ValidationContext is only needed for the generic GetValidationResult
        // path and for a CustomValidation method that takes one; a config validated
        // purely by other synthesized checks needs none (and so stays free of the
        // flagged ValidationContext ctor).
        bool needsContext = membersWithValidators.Any(m =>
            m.Validators.AsImmutableArray()
                .Any(v => v.Synthesis is null or CustomValidationCheck { PassesContext: true })
        );

        w.WriteLine(
            "/// <summary>Validate a constructed instance via its DataAnnotations attributes and IValidatableObject.</summary>"
        );
        // The ValidationContext ctor is the only RequiresUnreferencedCode surface
        // reached here: it lazily resolves a DisplayName via reflection when one
        // isn't supplied. We set MemberName/DisplayName explicitly for every member,
        // and every reflecting attribute is either synthesized away or refused
        // (ENVR0020), so this suppression is honest.
        if (needsContext)
        {
            w.WriteLine(
                "[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("
                    + "\"Trimming\", \"IL2026\", "
                    + "Justification = \"DisplayName is supplied explicitly; no member metadata is reflected at runtime.\")]"
            );
        }
        w.WriteLine($"private static {t} __Validate({t} instance)");
        w.WriteLine("{");
        w.Indent++;
        w.WriteLine("global::System.Collections.Generic.List<string>? __failures = null;");

        if (needsContext)
        {
            w.WriteLine($"var __ctx = new {ctxType}(instance);");
        }

        for (int mi = 0; mi < membersWithValidators.Length; mi++)
        {
            var m = membersWithValidators[mi];
            var displayExpr =
                m.DisplayNameExpression
                ?? Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(
                    m.MemberName,
                    quote: true
                );
            var validators = m.Validators.AsImmutableArray();
            bool memberUsesContext = validators.Any(v =>
                v.Synthesis is null or CustomValidationCheck { PassesContext: true }
            );
            if (memberUsesContext)
            {
                w.WriteLine($"__ctx.MemberName = \"{m.MemberName}\";");
                w.WriteLine($"__ctx.DisplayName = {displayExpr};");
            }
            for (int vi = 0; vi < validators.Length; vi++)
            {
                var v = validators[vi];
                var field = fieldNames[mi][vi];
                if (v.Synthesis is { } synth)
                {
                    EmitSynthesizedCheck(w, synth, m.MemberName, field, displayExpr);
                }
                else
                {
                    w.WriteLine("{");
                    w.Indent++;
                    w.WriteLine(
                        $"var __r = {field}.GetValidationResult(instance.{m.MemberName}, __ctx);"
                    );
                    // Fall back to a message built from the (already-set) display
                    // name when the attribute supplies none.
                    w.WriteLine(
                        "if (__r is not null) (__failures ??= new()).Add(__r.ErrorMessage ?? "
                            + "($\"Validation failed for '{__ctx.DisplayName}'.\"));"
                    );
                    w.Indent--;
                    w.WriteLine("}");
                }
            }
        }

        if (target.ImplementsIValidatableObject)
        {
            w.WriteLine(
                $"foreach (var __r in ((global::System.ComponentModel.DataAnnotations.IValidatableObject)instance).Validate(new {ctxType}(instance)))"
            );
            w.WriteLine("{");
            w.Indent++;
            w.WriteLine(
                "if (__r is not null) (__failures ??= new()).Add(__r.ErrorMessage ?? \"Validation failed.\");"
            );
            w.Indent--;
            w.WriteLine("}");
        }

        w.WriteLine("if (__failures is { Count: > 0 })");
        w.WriteLine("{");
        w.Indent++;
        w.WriteLine(
            $"throw new global::Enver.EnvValidationException(\"Configuration '{target.SimpleTypeName}' is invalid: \" "
                + "+ global::System.String.Join(\"; \", __failures), __failures);"
        );
        w.Indent--;
        w.WriteLine("}");
        w.WriteLine("return instance;");
        w.Indent--;
        w.WriteLine("}");
    }

    private static void EmitSynthesizedCheck(
        IndentedTextWriter w,
        SynthesizedCheck check,
        string memberName,
        string field,
        string displayExpr
    )
    {
        switch (check)
        {
            case LengthCheck length:
                EmitLengthCheck(w, memberName, length, field, displayExpr);
                break;
            case CompareCheck compare:
                EmitCompareCheck(w, memberName, compare, field, displayExpr);
                break;
            case CustomValidationCheck custom:
                EmitCustomValidationCheck(w, memberName, custom, displayExpr);
                break;
            default:
                throw new InvalidOperationException(
                    $"Unhandled synthesis kind: {check.GetType().Name}"
                );
        }
    }

    private static void EmitLengthCheck(
        IndentedTextWriter w,
        string memberName,
        LengthCheck ls,
        string field,
        string displayExpr
    )
    {
        var conditions = new List<string>(2);
        if (ls.MinBoundExpression is not null)
        {
            conditions.Add($"__len < {ls.MinBoundExpression}");
        }
        if (ls.MaxBoundExpression is not null)
        {
            conditions.Add($"__len > {ls.MaxBoundExpression}");
        }

        w.WriteLine("{");
        w.Indent++;
        w.WriteLine($"var __v = instance.{memberName};");
        w.WriteLine("if (__v is not null)");
        w.WriteLine("{");
        w.Indent++;
        w.WriteLine($"var __len = __v.{ls.LengthMember};");
        w.WriteLine($"if ({string.Join(" || ", conditions)})");
        w.WriteLine("{");
        w.Indent++;
        w.WriteLine($"(__failures ??= new()).Add({field}.FormatErrorMessage({displayExpr}));");
        w.Indent--;
        w.WriteLine("}");
        w.Indent--;
        w.WriteLine("}");
        w.Indent--;
        w.WriteLine("}");
    }

    private static void EmitCompareCheck(
        IndentedTextWriter w,
        string memberName,
        CompareCheck compare,
        string field,
        string displayExpr
    )
    {
        w.WriteLine(
            $"if (!global::System.Object.Equals(instance.{memberName}, instance.{compare.OtherMember}))"
        );
        w.WriteLine("{");
        w.Indent++;
        w.WriteLine($"(__failures ??= new()).Add({field}.FormatErrorMessage({displayExpr}));");
        w.Indent--;
        w.WriteLine("}");
    }

    private static void EmitCustomValidationCheck(
        IndentedTextWriter w,
        string memberName,
        CustomValidationCheck custom,
        string displayExpr
    )
    {
        // Reflection-free equivalent of CustomValidationAttribute: call the user's
        // static validator directly. The returned ValidationResult carries the
        // message (Success is null), so no attribute or FormatErrorMessage is used.
        var contextArg = custom.PassesContext ? ", __ctx" : "";
        w.WriteLine("{");
        w.Indent++;
        w.WriteLine(
            $"var __r = {custom.ValidatorTypeFullyQualifiedName}.{custom.MethodName}"
                + $"(instance.{memberName}{contextArg});"
        );
        w.WriteLine(
            "if (__r is not null) (__failures ??= new()).Add(__r.ErrorMessage ?? "
                + $"(\"Validation failed for '\" + {displayExpr} + \"'.\"));"
        );
        w.Indent--;
        w.WriteLine("}");
    }

    #endregion

    #region Helpers

    private enum EffectiveRequirement
    {
        Required,
        Optional,
    }

    private static EffectiveRequirement ResolveRequirement(BindingMember m)
    {
        // Explicit attribute
        if (m.Requirement == EnvRequirement.Required)
        {
            return EffectiveRequirement.Required;
        }

        // Explicit attribute
        if (m.Requirement == EnvRequirement.Optional)
        {
            return EffectiveRequirement.Optional;
        }

        // Inferred path:
        if (m.HasRequiredKeyword)
        {
            return EffectiveRequirement.Required;
        }

        if (m.CSharpInitializerExpression is not null)
        {
            return EffectiveRequirement.Optional;
        }

        if (m.TypeIsNullable)
        {
            return EffectiveRequirement.Optional;
        }

        return EffectiveRequirement.Required;
    }

    private static string StorageTypeOf(BindingMember m)
    {
        // For optional members we want the storage to be nullable so the
        // default-fallback path can leave it untouched. For required we use
        // the declared type as-is.
        var declared = m.TypeFullyQualifiedName;
        return ResolveRequirement(m) switch
        {
            EffectiveRequirement.Required => declared,
            _ => m.TypeIsNullable ? declared : declared + "?",
        };
    }

    private static BindingMember? TryFindMember(BindingTarget target, string memberName)
    {
        foreach (var m in target.Members.AsImmutableArray())
        {
            if (m.MemberName == memberName)
            {
                return m;
            }
        }
        return null;
    }

    #endregion
}
