<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../build/TestProject.props" />

  <PropertyGroup>
    <RootNamespace>Enver.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Enver.Binding/Enver.Binding.csproj" />
    <ProjectReference
      Include="../../src/Enver.Binding.Generator/Enver.Binding.Generator.csproj"
      ReferenceOutputAssembly="true"
    />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
  </ItemGroup>
</Project>
