<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../build/Library.props" />

  <PropertyGroup>
    <Description>Loads .env files into an in-memory dictionary.</Description>
    <RootNamespace>Enver</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Enver/Enver.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Enver.InMemory.Tests" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
